/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : test

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2022-12-28 13:30:19
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for district
-- ----------------------------
DROP TABLE IF EXISTS `district`;
CREATE TABLE `district` (
  `code` int(4) NOT NULL,
  `name_th` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `name_en` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `province_code` int(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of district
-- ----------------------------
INSERT INTO `district` VALUES ('1001', 'เขตพระนคร', 'Khet Phra Nakhon', '10');
INSERT INTO `district` VALUES ('1002', 'เขตดุสิต', 'Khet Dusit', '10');
INSERT INTO `district` VALUES ('1003', 'เขตหนองจอก', 'Khet  Nong Chok', '10');
INSERT INTO `district` VALUES ('1004', 'เขตบางรัก', 'Khet Bang Rak', '10');
INSERT INTO `district` VALUES ('1005', 'เขตบางเขน', 'Khet Bang Khen', '10');
INSERT INTO `district` VALUES ('1006', 'เขตบางกะปิ', 'Khet Bang Kapi', '10');
INSERT INTO `district` VALUES ('1007', 'เขตปทุมวัน', 'Khet Pathum Wan', '10');
INSERT INTO `district` VALUES ('1008', 'เขตป้อมปราบศัตรูพ่าย', 'Khet Pom Prap Sattru Phai', '10');
INSERT INTO `district` VALUES ('1009', 'เขตพระโขนง', 'Khet Phra Khanong', '10');
INSERT INTO `district` VALUES ('1010', 'เขตมีนบุรี', 'Khet Min Buri', '10');
INSERT INTO `district` VALUES ('1011', 'เขตลาดกระบัง', 'Khet Lat Krabang', '10');
INSERT INTO `district` VALUES ('1012', 'เขตยานนาวา', 'Khet Yan Nawa', '10');
INSERT INTO `district` VALUES ('1013', 'เขตสัมพันธวงศ์', 'Khet Samphanthawong', '10');
INSERT INTO `district` VALUES ('1014', 'เขตพญาไท', 'Khet Phaya Thai', '10');
INSERT INTO `district` VALUES ('1015', 'เขตธนบุรี', 'Khet Thon Buri', '10');
INSERT INTO `district` VALUES ('1016', 'เขตบางกอกใหญ่', 'Khet Bangkok Yai', '10');
INSERT INTO `district` VALUES ('1017', 'เขตห้วยขวาง', 'Khet Huai Khwang', '10');
INSERT INTO `district` VALUES ('1018', 'เขตคลองสาน', 'Khet Khlong San', '10');
INSERT INTO `district` VALUES ('1019', 'เขตตลิ่งชัน', 'Khet Taling Chan', '10');
INSERT INTO `district` VALUES ('1020', 'เขตบางกอกน้อย', 'Khet Bangkok Noi', '10');
INSERT INTO `district` VALUES ('1021', 'เขตบางขุนเทียน', 'Khet Bang Khun Thian', '10');
INSERT INTO `district` VALUES ('1022', 'เขตภาษีเจริญ', 'Khet Phasi Charoen', '10');
INSERT INTO `district` VALUES ('1023', 'เขตหนองแขม', 'Khet Nong Khaem', '10');
INSERT INTO `district` VALUES ('1024', 'เขตราษฎร์บูรณะ', 'Khet Rat Burana', '10');
INSERT INTO `district` VALUES ('1025', 'เขตบางพลัด', 'Khet Bang Phlat', '10');
INSERT INTO `district` VALUES ('1026', 'เขตดินแดง', 'Khet Din Daeng', '10');
INSERT INTO `district` VALUES ('1027', 'เขตบึงกุ่ม', 'Khet Bueng Kum', '10');
INSERT INTO `district` VALUES ('1028', 'เขตสาทร', 'Khet Sathon', '10');
INSERT INTO `district` VALUES ('1029', 'เขตบางซื่อ', 'Khet Bang Sue', '10');
INSERT INTO `district` VALUES ('1030', 'เขตจตุจักร', 'Khet Chatuchak', '10');
INSERT INTO `district` VALUES ('1031', 'เขตบางคอแหลม', 'Khet Bang Kho Laem', '10');
INSERT INTO `district` VALUES ('1032', 'เขตประเวศ', 'Khet Prawet', '10');
INSERT INTO `district` VALUES ('1033', 'เขตคลองเตย', 'Khet Khlong Toei', '10');
INSERT INTO `district` VALUES ('1034', 'เขตสวนหลวง', 'Khet Suan Luang', '10');
INSERT INTO `district` VALUES ('1035', 'เขตจอมทอง', 'Khet Chom Thong', '10');
INSERT INTO `district` VALUES ('1036', 'เขตดอนเมือง', 'Khet Don Mueang', '10');
INSERT INTO `district` VALUES ('1037', 'เขตราชเทวี', 'Khet Ratchathewi', '10');
INSERT INTO `district` VALUES ('1038', 'เขตลาดพร้าว', 'Khet Lat Phrao', '10');
INSERT INTO `district` VALUES ('1039', 'เขตวัฒนา', 'Khet Watthana', '10');
INSERT INTO `district` VALUES ('1040', 'เขตบางแค', 'Khet Bang Khae', '10');
INSERT INTO `district` VALUES ('1041', 'เขตหลักสี่', 'Khet Lak Si', '10');
INSERT INTO `district` VALUES ('1042', 'เขตสายไหม', 'Khet Sai Mai', '10');
INSERT INTO `district` VALUES ('1043', 'เขตคันนายาว', 'Khet Khan Na Yao', '10');
INSERT INTO `district` VALUES ('1044', 'เขตสะพานสูง', 'Khet Saphan Sung', '10');
INSERT INTO `district` VALUES ('1045', 'เขตวังทองหลาง', 'Khet Wang Thonglang', '10');
INSERT INTO `district` VALUES ('1046', 'เขตคลองสามวา', 'Khet Khlong Sam Wa', '10');
INSERT INTO `district` VALUES ('1047', 'เขตบางนา', 'Khet Bang Na', '10');
INSERT INTO `district` VALUES ('1048', 'เขตทวีวัฒนา', 'Khet Thawi Watthana', '10');
INSERT INTO `district` VALUES ('1049', 'เขตทุ่งครุ', 'Khet Thung Khru', '10');
INSERT INTO `district` VALUES ('1050', 'เขตบางบอน', 'Khet Bang Bon', '10');
INSERT INTO `district` VALUES ('1099', 'สำนักทะเบียนกลาง', '', '10');
INSERT INTO `district` VALUES ('1101', 'เมืองสมุทรปราการ', 'Mueang Samut Prakan', '11');
INSERT INTO `district` VALUES ('1102', 'บางบ่อ', 'Bang Bo', '11');
INSERT INTO `district` VALUES ('1103', 'บางพลี', 'Bang Phli', '11');
INSERT INTO `district` VALUES ('1104', 'พระประแดง', 'Phra Pradaeng', '11');
INSERT INTO `district` VALUES ('1105', 'พระสมุทรเจดีย์', 'Phra Samut Chedi', '11');
INSERT INTO `district` VALUES ('1106', 'บางเสาธง', 'Bang Sao Thong', '11');
INSERT INTO `district` VALUES ('1201', 'เมืองนนทบุรี', 'Mueang Nonthaburi', '12');
INSERT INTO `district` VALUES ('1202', 'บางกรวย', 'Bang Kruai', '12');
INSERT INTO `district` VALUES ('1203', 'บางใหญ่', 'Bang Yai', '12');
INSERT INTO `district` VALUES ('1204', 'บางบัวทอง', 'Bang Bua Thong', '12');
INSERT INTO `district` VALUES ('1205', 'ไทรน้อย', 'Sai Noi', '12');
INSERT INTO `district` VALUES ('1206', 'ปากเกร็ด', 'Pak Kret', '12');
INSERT INTO `district` VALUES ('1301', 'เมืองปทุมธานี', 'Mueang Pathum Thani', '13');
INSERT INTO `district` VALUES ('1302', 'คลองหลวง', 'Khlong Luang', '13');
INSERT INTO `district` VALUES ('1303', 'ธัญบุรี', 'Thanyaburi', '13');
INSERT INTO `district` VALUES ('1304', 'หนองเสือ', 'Nong Suea', '13');
INSERT INTO `district` VALUES ('1305', 'ลาดหลุมแก้ว', 'Lat Lum Kaeo', '13');
INSERT INTO `district` VALUES ('1306', 'ลำลูกกา', 'Lam Luk Ka', '13');
INSERT INTO `district` VALUES ('1307', 'สามโคก', 'Sam Khok', '13');
INSERT INTO `district` VALUES ('1401', 'พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', '14');
INSERT INTO `district` VALUES ('1402', 'ท่าเรือ', 'Tha Ruea', '14');
INSERT INTO `district` VALUES ('1403', 'นครหลวง', 'Nakhon Luang', '14');
INSERT INTO `district` VALUES ('1404', 'บางไทร', 'Bang Sai', '14');
INSERT INTO `district` VALUES ('1405', 'บางบาล', 'Bang Ban', '14');
INSERT INTO `district` VALUES ('1406', 'บางปะอิน', 'Bang Pa-in', '14');
INSERT INTO `district` VALUES ('1407', 'บางปะหัน', 'Bang Pahan', '14');
INSERT INTO `district` VALUES ('1408', 'ผักไห่', 'Phak Hai', '14');
INSERT INTO `district` VALUES ('1409', 'ภาชี', 'Phachi', '14');
INSERT INTO `district` VALUES ('1410', 'ลาดบัวหลวง', 'Lat Bua Luang', '14');
INSERT INTO `district` VALUES ('1411', 'วังน้อย', 'Wang Noi', '14');
INSERT INTO `district` VALUES ('1412', 'เสนา', 'Sena', '14');
INSERT INTO `district` VALUES ('1413', 'บางซ้าย', 'Bang Sai', '14');
INSERT INTO `district` VALUES ('1414', 'อุทัย', 'Uthai', '14');
INSERT INTO `district` VALUES ('1415', 'มหาราช', 'Maha Rat', '14');
INSERT INTO `district` VALUES ('1416', 'บ้านแพรก', 'Ban Phraek', '14');
INSERT INTO `district` VALUES ('1501', 'เมืองอ่างทอง', 'Mueang Ang Thong', '15');
INSERT INTO `district` VALUES ('1502', 'ไชโย', 'Chaiyo', '15');
INSERT INTO `district` VALUES ('1503', 'ป่าโมก', 'Pa Mok', '15');
INSERT INTO `district` VALUES ('1504', 'โพธิ์ทอง', 'Pho Thong', '15');
INSERT INTO `district` VALUES ('1505', 'แสวงหา', 'Sawaeng Ha', '15');
INSERT INTO `district` VALUES ('1506', 'วิเศษชัยชาญ', 'Wiset Chai Chan', '15');
INSERT INTO `district` VALUES ('1507', 'สามโก้', 'Samko', '15');
INSERT INTO `district` VALUES ('1601', 'เมืองลพบุรี', 'Mueang Lop Buri', '16');
INSERT INTO `district` VALUES ('1602', 'พัฒนานิคม', 'Phatthana Nikhom', '16');
INSERT INTO `district` VALUES ('1603', 'โคกสำโรง', 'Khok Samrong', '16');
INSERT INTO `district` VALUES ('1604', 'ชัยบาดาล', 'Chai Badan', '16');
INSERT INTO `district` VALUES ('1605', 'ท่าวุ้ง', 'Tha Wung', '16');
INSERT INTO `district` VALUES ('1606', 'บ้านหมี่', 'Ban Mi', '16');
INSERT INTO `district` VALUES ('1607', 'ท่าหลวง', 'Tha Luang', '16');
INSERT INTO `district` VALUES ('1608', 'สระโบสถ์', 'Sa Bot', '16');
INSERT INTO `district` VALUES ('1609', 'โคกเจริญ', 'Khok Charoen', '16');
INSERT INTO `district` VALUES ('1610', 'ลำสนธิ', 'Lam Sonthi', '16');
INSERT INTO `district` VALUES ('1611', 'หนองม่วง', 'Nong Muang', '16');
INSERT INTO `district` VALUES ('1701', 'เมืองสิงห์บุรี', 'Mueang Sing Buri', '17');
INSERT INTO `district` VALUES ('1702', 'บางระจัน', 'Bang Rachan', '17');
INSERT INTO `district` VALUES ('1703', 'ค่ายบางระจัน', 'Khai Bang Rachan', '17');
INSERT INTO `district` VALUES ('1704', 'พรหมบุรี', 'Phrom Buri', '17');
INSERT INTO `district` VALUES ('1705', 'ท่าช้าง', 'Tha Chang', '17');
INSERT INTO `district` VALUES ('1706', 'อินทร์บุรี', 'In Buri', '17');
INSERT INTO `district` VALUES ('1801', 'เมืองชัยนาท', 'Mueang Chai Nat', '18');
INSERT INTO `district` VALUES ('1802', 'มโนรมย์', 'Manorom', '18');
INSERT INTO `district` VALUES ('1803', 'วัดสิงห์', 'Wat Sing', '18');
INSERT INTO `district` VALUES ('1804', 'สรรพยา', 'Sapphaya', '18');
INSERT INTO `district` VALUES ('1805', 'สรรคบุรี', 'Sankhaburi', '18');
INSERT INTO `district` VALUES ('1806', 'หันคา', 'Hankha', '18');
INSERT INTO `district` VALUES ('1807', 'หนองมะโมง', 'Nong Mamong', '18');
INSERT INTO `district` VALUES ('1808', 'เนินขาม', 'Noen Kham', '18');
INSERT INTO `district` VALUES ('1901', 'เมืองสระบุรี', 'Mueang Saraburi', '19');
INSERT INTO `district` VALUES ('1902', 'แก่งคอย', 'Kaeng Khoi', '19');
INSERT INTO `district` VALUES ('1903', 'หนองแค', 'Nong Khae', '19');
INSERT INTO `district` VALUES ('1904', 'วิหารแดง', 'Wihan Daeng', '19');
INSERT INTO `district` VALUES ('1905', 'หนองแซง', 'Nong Saeng', '19');
INSERT INTO `district` VALUES ('1906', 'บ้านหมอ', 'Ban Mo', '19');
INSERT INTO `district` VALUES ('1907', 'ดอนพุด', 'Don Phut', '19');
INSERT INTO `district` VALUES ('1908', 'หนองโดน', 'Nong Don', '19');
INSERT INTO `district` VALUES ('1909', 'พระพุทธบาท', 'Phra Phutthabat', '19');
INSERT INTO `district` VALUES ('1910', 'เสาไห้', 'Sao Hai', '19');
INSERT INTO `district` VALUES ('1911', 'มวกเหล็ก', 'Muak Lek', '19');
INSERT INTO `district` VALUES ('1912', 'วังม่วง', 'Wang Muang', '19');
INSERT INTO `district` VALUES ('1913', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat', '19');
INSERT INTO `district` VALUES ('2001', 'เมืองชลบุรี', 'Mueang Chon Buri', '20');
INSERT INTO `district` VALUES ('2002', 'บ้านบึง', 'Ban Bueng', '20');
INSERT INTO `district` VALUES ('2003', 'หนองใหญ่', 'Nong Yai', '20');
INSERT INTO `district` VALUES ('2004', 'บางละมุง', 'Bang Lamung', '20');
INSERT INTO `district` VALUES ('2005', 'พานทอง', 'Phan Thong', '20');
INSERT INTO `district` VALUES ('2006', 'พนัสนิคม', 'Phanat Nikhom', '20');
INSERT INTO `district` VALUES ('2007', 'ศรีราชา', 'Si Racha', '20');
INSERT INTO `district` VALUES ('2008', 'เกาะสีชัง', 'Ko Sichang', '20');
INSERT INTO `district` VALUES ('2009', 'สัตหีบ', 'Sattahip', '20');
INSERT INTO `district` VALUES ('2010', 'บ่อทอง', 'Bo Thong', '20');
INSERT INTO `district` VALUES ('2011', 'เกาะจันทร์', 'Ko Chan', '20');
INSERT INTO `district` VALUES ('2101', 'เมืองระยอง', 'Mueang Rayong', '21');
INSERT INTO `district` VALUES ('2102', 'บ้านฉาง', 'Ban Chang', '21');
INSERT INTO `district` VALUES ('2103', 'แกลง', 'Klaeng', '21');
INSERT INTO `district` VALUES ('2104', 'วังจันทร์', 'Wang Chan', '21');
INSERT INTO `district` VALUES ('2105', 'บ้านค่าย', 'Ban Khai', '21');
INSERT INTO `district` VALUES ('2106', 'ปลวกแดง', 'Pluak Daeng', '21');
INSERT INTO `district` VALUES ('2107', 'เขาชะเมา', 'Khao Chamao', '21');
INSERT INTO `district` VALUES ('2108', 'นิคมพัฒนา', 'Nikhom Phatthana', '21');
INSERT INTO `district` VALUES ('2201', 'เมืองจันทบุรี', 'Mueang Chanthaburi', '22');
INSERT INTO `district` VALUES ('2202', 'ขลุง', 'Khlung', '22');
INSERT INTO `district` VALUES ('2203', 'ท่าใหม่', 'Tha Mai', '22');
INSERT INTO `district` VALUES ('2204', 'โป่งน้ำร้อน', 'Pong Nam Ron', '22');
INSERT INTO `district` VALUES ('2205', 'มะขาม', 'Makham', '22');
INSERT INTO `district` VALUES ('2206', 'แหลมสิงห์', 'Laem Sing', '22');
INSERT INTO `district` VALUES ('2207', 'สอยดาว', 'Soi Dao', '22');
INSERT INTO `district` VALUES ('2208', 'แก่งหางแมว', 'Kaeng Hang Maeo', '22');
INSERT INTO `district` VALUES ('2209', 'นายายอาม', 'Na Yai Am', '22');
INSERT INTO `district` VALUES ('2210', 'เขาคิชฌกูฏ', 'Khoa Khitchakut', '22');
INSERT INTO `district` VALUES ('2301', 'เมืองตราด', 'Mueang Trat', '23');
INSERT INTO `district` VALUES ('2302', 'คลองใหญ่', 'Khlong Yai', '23');
INSERT INTO `district` VALUES ('2303', 'เขาสมิง', 'Khao Saming', '23');
INSERT INTO `district` VALUES ('2304', 'บ่อไร่', 'Bo Rai', '23');
INSERT INTO `district` VALUES ('2305', 'แหลมงอบ', 'Laem Ngop', '23');
INSERT INTO `district` VALUES ('2306', 'เกาะกูด', 'Ko Kut', '23');
INSERT INTO `district` VALUES ('2307', 'เกาะช้าง', 'Ko Chang', '23');
INSERT INTO `district` VALUES ('2401', 'เมืองฉะเชิงเทรา', 'Mueang Chachoengsao', '24');
INSERT INTO `district` VALUES ('2402', 'บางคล้า', 'Bang Khla', '24');
INSERT INTO `district` VALUES ('2403', 'บางน้ำเปรี้ยว', 'Bang Nam Priao', '24');
INSERT INTO `district` VALUES ('2404', 'บางปะกง', 'Bang Pakong', '24');
INSERT INTO `district` VALUES ('2405', 'บ้านโพธิ์', 'Ban Pho', '24');
INSERT INTO `district` VALUES ('2406', 'พนมสารคาม', 'Phanom Sarakham', '24');
INSERT INTO `district` VALUES ('2407', 'ราชสาส์น', 'Ratchasan', '24');
INSERT INTO `district` VALUES ('2408', 'สนามชัยเขต', 'Sanam Chai Khet', '24');
INSERT INTO `district` VALUES ('2409', 'แปลงยาว', 'Plaeng Yao', '24');
INSERT INTO `district` VALUES ('2410', 'ท่าตะเกียบ', 'Tha Takiap', '24');
INSERT INTO `district` VALUES ('2411', 'คลองเขื่อน', 'Khlong Khuean', '24');
INSERT INTO `district` VALUES ('2501', 'เมืองปราจีนบุรี', 'Mueang Prachin Buri', '25');
INSERT INTO `district` VALUES ('2502', 'กบินทร์บุรี', 'Kabin Buri', '25');
INSERT INTO `district` VALUES ('2503', 'นาดี', 'Na Di', '25');
INSERT INTO `district` VALUES ('2506', 'บ้านสร้าง', 'Ban Sang', '25');
INSERT INTO `district` VALUES ('2507', 'ประจันตคาม', 'Prachantakham', '25');
INSERT INTO `district` VALUES ('2508', 'ศรีมหาโพธิ', 'Si Maha Phot', '25');
INSERT INTO `district` VALUES ('2509', 'ศรีมโหสถ', 'Si Mahosot', '25');
INSERT INTO `district` VALUES ('2601', 'เมืองนครนายก', 'Mueang Nakhon Nayok', '26');
INSERT INTO `district` VALUES ('2602', 'ปากพลี', 'Pak Phli', '26');
INSERT INTO `district` VALUES ('2603', 'บ้านนา', 'Ban Na', '26');
INSERT INTO `district` VALUES ('2604', 'องครักษ์', 'Ongkharak', '26');
INSERT INTO `district` VALUES ('2701', 'เมืองสระแก้ว', 'Mueang Sa Kaeo', '27');
INSERT INTO `district` VALUES ('2702', 'คลองหาด', 'Khlong Hat', '27');
INSERT INTO `district` VALUES ('2703', 'ตาพระยา', 'Ta Phraya', '27');
INSERT INTO `district` VALUES ('2704', 'วังน้ำเย็น', 'Wang Nam Yen', '27');
INSERT INTO `district` VALUES ('2705', 'วัฒนานคร', 'Watthana Nakhon', '27');
INSERT INTO `district` VALUES ('2706', 'อรัญประเทศ', 'Aranyaprathet', '27');
INSERT INTO `district` VALUES ('2707', 'เขาฉกรรจ์', 'Khao Chakan', '27');
INSERT INTO `district` VALUES ('2708', 'โคกสูง', 'Khok Sung', '27');
INSERT INTO `district` VALUES ('2709', 'วังสมบูรณ์', 'Wang Sombun', '27');
INSERT INTO `district` VALUES ('3001', 'เมืองนครราชสีมา', 'Mueang Nakhon Ratchasima', '30');
INSERT INTO `district` VALUES ('3002', 'ครบุรี', 'Khon Buri', '30');
INSERT INTO `district` VALUES ('3003', 'เสิงสาง', 'Soeng Sang', '30');
INSERT INTO `district` VALUES ('3004', 'คง', 'Khong', '30');
INSERT INTO `district` VALUES ('3005', 'บ้านเหลื่อม', 'Ban Lueam', '30');
INSERT INTO `district` VALUES ('3006', 'จักราช', 'Chakkarat', '30');
INSERT INTO `district` VALUES ('3007', 'โชคชัย', 'Chok Chai', '30');
INSERT INTO `district` VALUES ('3008', 'ด่านขุนทด', 'Dan Khun Thot', '30');
INSERT INTO `district` VALUES ('3009', 'โนนไทย', 'Non Thai', '30');
INSERT INTO `district` VALUES ('3010', 'โนนสูง', 'Non Sung', '30');
INSERT INTO `district` VALUES ('3011', 'ขามสะแกแสง', 'Kham Sakaesaeng', '30');
INSERT INTO `district` VALUES ('3012', 'บัวใหญ่', 'Bua Yai', '30');
INSERT INTO `district` VALUES ('3013', 'ประทาย', 'Prathai', '30');
INSERT INTO `district` VALUES ('3014', 'ปักธงชัย', 'Pak Thong Chai', '30');
INSERT INTO `district` VALUES ('3015', 'พิมาย', 'Phimai', '30');
INSERT INTO `district` VALUES ('3016', 'ห้วยแถลง', 'Huai Thalaeng', '30');
INSERT INTO `district` VALUES ('3017', 'ชุมพวง', 'Chum Phuang', '30');
INSERT INTO `district` VALUES ('3018', 'สูงเนิน', 'Sung Noen', '30');
INSERT INTO `district` VALUES ('3019', 'ขามทะเลสอ', 'Kham Thale So', '30');
INSERT INTO `district` VALUES ('3020', 'สีคิ้ว', 'Sikhio', '30');
INSERT INTO `district` VALUES ('3021', 'ปากช่อง', 'Pak Chong', '30');
INSERT INTO `district` VALUES ('3022', 'หนองบุญมาก', 'Nong Bunnak', '30');
INSERT INTO `district` VALUES ('3023', 'แก้งสนามนาง', 'Kaeng Sanam Nang', '30');
INSERT INTO `district` VALUES ('3024', 'โนนแดง', 'Non Daeng', '30');
INSERT INTO `district` VALUES ('3025', 'วังน้ำเขียว', 'Wang Nam Khiao', '30');
INSERT INTO `district` VALUES ('3026', 'เทพารักษ์', 'Thepharak', '30');
INSERT INTO `district` VALUES ('3027', 'เมืองยาง', 'Mueang Yang', '30');
INSERT INTO `district` VALUES ('3028', 'พระทองคำ', 'Phra Thong Kham', '30');
INSERT INTO `district` VALUES ('3029', 'ลำทะเมนชัย', 'Lam Thamenchai', '30');
INSERT INTO `district` VALUES ('3030', 'บัวลาย', 'Bua Lai', '30');
INSERT INTO `district` VALUES ('3031', 'สีดา', 'Sida', '30');
INSERT INTO `district` VALUES ('3032', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat', '30');
INSERT INTO `district` VALUES ('3101', 'เมืองบุรีรัมย์', 'Mueang Buri Ram', '31');
INSERT INTO `district` VALUES ('3102', 'คูเมือง', 'Khu Mueang', '31');
INSERT INTO `district` VALUES ('3103', 'กระสัง', 'Krasang', '31');
INSERT INTO `district` VALUES ('3104', 'นางรอง', 'Nang Rong', '31');
INSERT INTO `district` VALUES ('3105', 'หนองกี่', 'Nong Ki', '31');
INSERT INTO `district` VALUES ('3106', 'ละหานทราย', 'Lahan Sai', '31');
INSERT INTO `district` VALUES ('3107', 'ประโคนชัย', 'Prakhon Chai', '31');
INSERT INTO `district` VALUES ('3108', 'บ้านกรวด', 'Ban Kruat', '31');
INSERT INTO `district` VALUES ('3109', 'พุทไธสง', 'Phutthaisong', '31');
INSERT INTO `district` VALUES ('3110', 'ลำปลายมาศ', 'Lam Plai Mat', '31');
INSERT INTO `district` VALUES ('3111', 'สตึก', 'Satuek', '31');
INSERT INTO `district` VALUES ('3112', 'ปะคำ', 'Pakham', '31');
INSERT INTO `district` VALUES ('3113', 'นาโพธิ์', 'Na Pho', '31');
INSERT INTO `district` VALUES ('3114', 'หนองหงส์', 'Nong Hong', '31');
INSERT INTO `district` VALUES ('3115', 'พลับพลาชัย', 'Phlapphla Chai', '31');
INSERT INTO `district` VALUES ('3116', 'ห้วยราช', 'Huai Rat', '31');
INSERT INTO `district` VALUES ('3117', 'โนนสุวรรณ', 'Non Suwan', '31');
INSERT INTO `district` VALUES ('3118', 'ชำนิ', 'Chamni', '31');
INSERT INTO `district` VALUES ('3119', 'บ้านใหม่ไชยพจน์', 'Ban Mai Chaiyaphot', '31');
INSERT INTO `district` VALUES ('3120', 'โนนดินแดง', 'Din Daeng', '31');
INSERT INTO `district` VALUES ('3121', 'บ้านด่าน', 'Ban Dan', '31');
INSERT INTO `district` VALUES ('3122', 'แคนดง', 'Khaen Dong', '31');
INSERT INTO `district` VALUES ('3123', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat', '31');
INSERT INTO `district` VALUES ('3201', 'เมืองสุรินทร์', 'Mueang Surin', '32');
INSERT INTO `district` VALUES ('3202', 'ชุมพลบุรี', 'Chumphon Buri', '32');
INSERT INTO `district` VALUES ('3203', 'ท่าตูม', 'Tha Tum', '32');
INSERT INTO `district` VALUES ('3204', 'จอมพระ', 'Chom Phra', '32');
INSERT INTO `district` VALUES ('3205', 'ปราสาท', 'Prasat', '32');
INSERT INTO `district` VALUES ('3206', 'กาบเชิง', 'Kap Choeng', '32');
INSERT INTO `district` VALUES ('3207', 'รัตนบุรี', 'Rattanaburi', '32');
INSERT INTO `district` VALUES ('3208', 'สนม', 'Sanom', '32');
INSERT INTO `district` VALUES ('3209', 'ศีขรภูมิ', 'Sikhoraphum', '32');
INSERT INTO `district` VALUES ('3210', 'สังขะ', 'Sangkha', '32');
INSERT INTO `district` VALUES ('3211', 'ลำดวน', 'Lamduan', '32');
INSERT INTO `district` VALUES ('3212', 'สำโรงทาบ', 'Samrong Thap', '32');
INSERT INTO `district` VALUES ('3213', 'บัวเชด', 'Buachet', '32');
INSERT INTO `district` VALUES ('3214', 'พนมดงรัก', 'Phanom Dong Rak', '32');
INSERT INTO `district` VALUES ('3215', 'ศรีณรงค์', 'Si Narong', '32');
INSERT INTO `district` VALUES ('3216', 'เขวาสินรินทร์', 'Khwao Sinarin', '32');
INSERT INTO `district` VALUES ('3217', 'โนนนารายณ์', 'Non Narai', '32');
INSERT INTO `district` VALUES ('3301', 'เมืองศรีสะเกษ', 'Mueang Si Sa Ket', '33');
INSERT INTO `district` VALUES ('3302', 'ยางชุมน้อย', 'Yang Chum Noi', '33');
INSERT INTO `district` VALUES ('3303', 'กันทรารมย์', 'Kanthararom', '33');
INSERT INTO `district` VALUES ('3304', 'กันทรลักษ์', 'Kantharalak', '33');
INSERT INTO `district` VALUES ('3305', 'ขุขันธ์', 'Khukhan', '33');
INSERT INTO `district` VALUES ('3306', 'ไพรบึง', 'Phrai Bueng', '33');
INSERT INTO `district` VALUES ('3307', 'ปรางค์กู่', 'Prang Ku', '33');
INSERT INTO `district` VALUES ('3308', 'ขุนหาญ', 'Khun Han', '33');
INSERT INTO `district` VALUES ('3309', 'ราษีไศล', 'Rasi Salai', '33');
INSERT INTO `district` VALUES ('3310', 'อุทุมพรพิสัย', 'Uthumphon Phisai', '33');
INSERT INTO `district` VALUES ('3311', 'บึงบูรพ์', 'Bueng Bun', '33');
INSERT INTO `district` VALUES ('3312', 'ห้วยทับทัน', 'Huai Thap Than', '33');
INSERT INTO `district` VALUES ('3313', 'โนนคูณ', 'Non Khun', '33');
INSERT INTO `district` VALUES ('3314', 'ศรีรัตนะ', 'Si Rattana', '33');
INSERT INTO `district` VALUES ('3315', 'น้ำเกลี้ยง', 'Si Rattana', '33');
INSERT INTO `district` VALUES ('3316', 'วังหิน', 'Wang Hin', '33');
INSERT INTO `district` VALUES ('3317', 'ภูสิงห์', 'Phu Sing', '33');
INSERT INTO `district` VALUES ('3318', 'เมืองจันทร์', 'Mueang Chan', '33');
INSERT INTO `district` VALUES ('3319', 'เบญจลักษ์', 'Benchalak', '33');
INSERT INTO `district` VALUES ('3320', 'พยุห์', 'Phayu', '33');
INSERT INTO `district` VALUES ('3321', 'โพธิ์ศรีสุวรรณ', 'Pho Si Suwan', '33');
INSERT INTO `district` VALUES ('3322', 'ศิลาลาด', 'Sila Lat', '33');
INSERT INTO `district` VALUES ('3401', 'เมืองอุบลราชธานี', 'Mueang Ubon Ratchathani', '34');
INSERT INTO `district` VALUES ('3402', 'ศรีเมืองใหม่', 'Si Mueang Mai', '34');
INSERT INTO `district` VALUES ('3403', 'โขงเจียม', 'Khong Chiam', '34');
INSERT INTO `district` VALUES ('3404', 'เขื่องใน', 'Khueang Nai', '34');
INSERT INTO `district` VALUES ('3405', 'เขมราฐ', 'Khemarat', '34');
INSERT INTO `district` VALUES ('3407', 'เดชอุดม', 'Det Udom', '34');
INSERT INTO `district` VALUES ('3408', 'นาจะหลวย', 'Na Chaluai', '34');
INSERT INTO `district` VALUES ('3409', 'น้ำยืน', 'Nam Yuen', '34');
INSERT INTO `district` VALUES ('3410', 'บุณฑริก', 'Buntharik', '34');
INSERT INTO `district` VALUES ('3411', 'ตระการพืชผล', 'Trakan Phuet Phon', '34');
INSERT INTO `district` VALUES ('3412', 'กุดข้าวปุ้น', 'Kut Khaopun', '34');
INSERT INTO `district` VALUES ('3414', 'ม่วงสามสิบ', 'Muang Sam Sip', '34');
INSERT INTO `district` VALUES ('3415', 'วารินชำราบ', 'Warin Chamrap', '34');
INSERT INTO `district` VALUES ('3419', 'พิบูลมังสาหาร', 'Phibun Mangsahan', '34');
INSERT INTO `district` VALUES ('3420', 'ตาลสุม', 'Tan Sum', '34');
INSERT INTO `district` VALUES ('3421', 'โพธิ์ไทร', 'Pho Sai', '34');
INSERT INTO `district` VALUES ('3422', 'สำโรง', 'Samrong', '34');
INSERT INTO `district` VALUES ('3424', 'ดอนมดแดง', 'Don Mot Daeng', '34');
INSERT INTO `district` VALUES ('3425', 'สิรินธร', 'Sirindhorn', '34');
INSERT INTO `district` VALUES ('3426', 'ทุ่งศรีอุดม', 'Thung Si Udom', '34');
INSERT INTO `district` VALUES ('3429', 'นาเยีย', 'Na Yia', '34');
INSERT INTO `district` VALUES ('3430', 'นาตาล', 'Na Tan', '34');
INSERT INTO `district` VALUES ('3431', 'เหล่าเสือโก้ก', 'Lao Suea Kok', '34');
INSERT INTO `district` VALUES ('3432', 'สว่างวีระวงศ์', 'Sawang Wirawong', '34');
INSERT INTO `district` VALUES ('3433', 'น้ำขุ่น', 'Nam Khun', '34');
INSERT INTO `district` VALUES ('3501', 'เมืองยโสธร', 'Mueang Yasothon', '35');
INSERT INTO `district` VALUES ('3502', 'ทรายมูล', 'Sai Mun', '35');
INSERT INTO `district` VALUES ('3503', 'กุดชุม', 'Kut Chum', '35');
INSERT INTO `district` VALUES ('3504', 'คำเขื่อนแก้ว', 'Kham Khuean Kaeo', '35');
INSERT INTO `district` VALUES ('3505', 'ป่าติ้ว', 'Pa Tio', '35');
INSERT INTO `district` VALUES ('3506', 'มหาชนะชัย', 'Maha Chana Chai', '35');
INSERT INTO `district` VALUES ('3507', 'ค้อวัง', 'Kho Wang', '35');
INSERT INTO `district` VALUES ('3508', 'เลิงนกทา', 'Loeng Nok Tha', '35');
INSERT INTO `district` VALUES ('3509', 'ไทยเจริญ', 'Thai Charoen', '35');
INSERT INTO `district` VALUES ('3601', 'เมืองชัยภูมิ', 'Mueang Chaiyaphum', '36');
INSERT INTO `district` VALUES ('3602', 'บ้านเขว้า', 'Ban Khwao', '36');
INSERT INTO `district` VALUES ('3603', 'คอนสวรรค์', 'Khon Sawan', '36');
INSERT INTO `district` VALUES ('3604', 'เกษตรสมบูรณ์', 'Kaset Sombun', '36');
INSERT INTO `district` VALUES ('3605', 'หนองบัวแดง', 'Nong Bua Daeng', '36');
INSERT INTO `district` VALUES ('3606', 'จัตุรัส', 'Chatturat', '36');
INSERT INTO `district` VALUES ('3607', 'บำเหน็จณรงค์', 'Bamnet Narong', '36');
INSERT INTO `district` VALUES ('3608', 'หนองบัวระเหว', 'Nong Bua Rawe', '36');
INSERT INTO `district` VALUES ('3609', 'เทพสถิต', 'Thep Sathit', '36');
INSERT INTO `district` VALUES ('3610', 'ภูเขียว', 'Phu Khiao', '36');
INSERT INTO `district` VALUES ('3611', 'บ้านแท่น', 'Ban Thaen', '36');
INSERT INTO `district` VALUES ('3612', 'แก้งคร้อ', 'Kaeng Khro', '36');
INSERT INTO `district` VALUES ('3613', 'คอนสาร', 'Khon San', '36');
INSERT INTO `district` VALUES ('3614', 'ภักดีชุมพล', 'Phakdi Chumphon', '36');
INSERT INTO `district` VALUES ('3615', 'เนินสง่า', 'Noen Sa-nga', '36');
INSERT INTO `district` VALUES ('3616', 'ซับใหญ่', 'Sap Yai', '36');
INSERT INTO `district` VALUES ('3701', 'เมืองอำนาจเจริญ', 'Mueang Amnat Charoen', '37');
INSERT INTO `district` VALUES ('3702', 'ชานุมาน', 'Chanuman', '37');
INSERT INTO `district` VALUES ('3703', 'ปทุมราชวงศา', 'Pathum Ratchawongsa', '37');
INSERT INTO `district` VALUES ('3704', 'พนา', 'Phana', '37');
INSERT INTO `district` VALUES ('3705', 'เสนางคนิคม', 'Senangkhanikhom', '37');
INSERT INTO `district` VALUES ('3706', 'หัวตะพาน', 'Hua Taphan', '37');
INSERT INTO `district` VALUES ('3707', 'ลืออำนาจ', 'Lue Amnat', '37');
INSERT INTO `district` VALUES ('3801', 'เมืองบึงกาฬ', 'Mueang Bueng Kan', '38');
INSERT INTO `district` VALUES ('3802', 'พรเจริญ', 'Phon Charoen', '38');
INSERT INTO `district` VALUES ('3803', 'โซ่พิสัย', 'So Phisai', '38');
INSERT INTO `district` VALUES ('3804', 'เซกา', 'Seka', '38');
INSERT INTO `district` VALUES ('3805', 'ปากคาด', 'Pak Khat', '38');
INSERT INTO `district` VALUES ('3806', 'บึงโขงหลง', 'Bueng Khong Long', '38');
INSERT INTO `district` VALUES ('3807', 'ศรีวิไล', 'Si Wilai', '38');
INSERT INTO `district` VALUES ('3808', 'บุ่งคล้า', 'Bung Khla', '38');
INSERT INTO `district` VALUES ('3901', 'เมืองหนองบัวลำภู', 'Mueang Nong Bua Lam Phu', '39');
INSERT INTO `district` VALUES ('3902', 'นากลาง', 'Na Klang', '39');
INSERT INTO `district` VALUES ('3903', 'โนนสัง', 'Non Sang', '39');
INSERT INTO `district` VALUES ('3904', 'ศรีบุญเรือง', 'Si Bun Rueang', '39');
INSERT INTO `district` VALUES ('3905', 'สุวรรณคูหา', 'Suwannakhuha', '39');
INSERT INTO `district` VALUES ('3906', 'นาวัง', 'Na Wang', '39');
INSERT INTO `district` VALUES ('4001', 'เมืองขอนแก่น', 'Mueang Khon Kaen', '40');
INSERT INTO `district` VALUES ('4002', 'บ้านฝาง', 'Ban Fang', '40');
INSERT INTO `district` VALUES ('4003', 'พระยืน', 'Phra Yuen', '40');
INSERT INTO `district` VALUES ('4004', 'หนองเรือ', 'Nong Ruea', '40');
INSERT INTO `district` VALUES ('4005', 'ชุมแพ', 'Chum Phae', '40');
INSERT INTO `district` VALUES ('4006', 'สีชมพู', 'Si Chomphu', '40');
INSERT INTO `district` VALUES ('4007', 'น้ำพอง', 'Nam Phong', '40');
INSERT INTO `district` VALUES ('4008', 'อุบลรัตน์', 'Ubolratana', '40');
INSERT INTO `district` VALUES ('4009', 'กระนวน', 'Kranuan', '40');
INSERT INTO `district` VALUES ('4010', 'บ้านไผ่', 'Ban Phai', '40');
INSERT INTO `district` VALUES ('4011', 'เปือยน้อย', 'Pueai Noi', '40');
INSERT INTO `district` VALUES ('4012', 'พล', 'Phon', '40');
INSERT INTO `district` VALUES ('4013', 'แวงใหญ่', 'Waeng Yai', '40');
INSERT INTO `district` VALUES ('4014', 'แวงน้อย', 'Waeng Noi', '40');
INSERT INTO `district` VALUES ('4015', 'หนองสองห้อง', 'Nong Song Hong', '40');
INSERT INTO `district` VALUES ('4016', 'ภูเวียง', 'Phu Wiang', '40');
INSERT INTO `district` VALUES ('4017', 'มัญจาคีรี', 'Mancha Khiri', '40');
INSERT INTO `district` VALUES ('4018', 'ชนบท', 'Chonnabot', '40');
INSERT INTO `district` VALUES ('4019', 'เขาสวนกวาง', 'Khao Suan Kwang', '40');
INSERT INTO `district` VALUES ('4020', 'ภูผาม่าน', 'Phu Pha Man', '40');
INSERT INTO `district` VALUES ('4021', 'ซำสูง', 'Sam Sung', '40');
INSERT INTO `district` VALUES ('4022', 'โคกโพธิ์ไชย', 'Khok Pho Chai', '40');
INSERT INTO `district` VALUES ('4023', 'หนองนาคำ', 'Nong Na Kham', '40');
INSERT INTO `district` VALUES ('4024', 'บ้านแฮด', 'Ban Haet', '40');
INSERT INTO `district` VALUES ('4025', 'โนนศิลา', 'Non Sila', '40');
INSERT INTO `district` VALUES ('4029', 'เวียงเก่า', 'Wiang Kao', '40');
INSERT INTO `district` VALUES ('4101', 'เมืองอุดรธานี', 'Mueang Udon Thani', '41');
INSERT INTO `district` VALUES ('4102', 'กุดจับ', 'Kut Chap', '41');
INSERT INTO `district` VALUES ('4103', 'หนองวัวซอ', 'Nong Wua So', '41');
INSERT INTO `district` VALUES ('4104', 'กุมภวาปี', 'Kumphawapi', '41');
INSERT INTO `district` VALUES ('4105', 'โนนสะอาด', 'Non Sa-at', '41');
INSERT INTO `district` VALUES ('4106', 'หนองหาน', 'Nong Han', '41');
INSERT INTO `district` VALUES ('4107', 'ทุ่งฝน', 'Thung Fon', '41');
INSERT INTO `district` VALUES ('4108', 'ไชยวาน', 'Chai Wan', '41');
INSERT INTO `district` VALUES ('4109', 'ศรีธาตุ', 'Si That', '41');
INSERT INTO `district` VALUES ('4110', 'วังสามหมอ', 'Wang Sam Mo', '41');
INSERT INTO `district` VALUES ('4111', 'บ้านดุง', 'Ban Dung', '41');
INSERT INTO `district` VALUES ('4117', 'บ้านผือ', 'Ban Phue', '41');
INSERT INTO `district` VALUES ('4118', 'น้ำโสม', 'Nam Som', '41');
INSERT INTO `district` VALUES ('4119', 'เพ็ญ', 'Phen', '41');
INSERT INTO `district` VALUES ('4120', 'สร้างคอม', 'Sang Khom', '41');
INSERT INTO `district` VALUES ('4121', 'หนองแสง', 'Nong Saeng', '41');
INSERT INTO `district` VALUES ('4122', 'นายูง', 'Na Yung', '41');
INSERT INTO `district` VALUES ('4123', 'พิบูลย์รักษ์', 'Phibun Rak', '41');
INSERT INTO `district` VALUES ('4124', 'กู่แก้ว', 'Ku Kaeo', '41');
INSERT INTO `district` VALUES ('4125', 'ประจักษ์ศิลปาคม', 'rachak-sinlapakhom', '41');
INSERT INTO `district` VALUES ('4201', 'เมืองเลย', 'Mueang Loei', '42');
INSERT INTO `district` VALUES ('4202', 'นาด้วง', 'Na Duang', '42');
INSERT INTO `district` VALUES ('4203', 'เชียงคาน', 'Chiang Khan', '42');
INSERT INTO `district` VALUES ('4204', 'ปากชม', 'Pak Chom', '42');
INSERT INTO `district` VALUES ('4205', 'ด่านซ้าย', 'Dan Sai', '42');
INSERT INTO `district` VALUES ('4206', 'นาแห้ว', 'Na Haeo', '42');
INSERT INTO `district` VALUES ('4207', 'ภูเรือ', 'Phu Ruea', '42');
INSERT INTO `district` VALUES ('4208', 'ท่าลี่', 'Tha Li', '42');
INSERT INTO `district` VALUES ('4209', 'วังสะพุง', 'Wang Saphung', '42');
INSERT INTO `district` VALUES ('4210', 'ภูกระดึง', 'Phu Kradueng', '42');
INSERT INTO `district` VALUES ('4211', 'ภูหลวง', 'Phu Luang', '42');
INSERT INTO `district` VALUES ('4212', 'ผาขาว', 'Pha Khao', '42');
INSERT INTO `district` VALUES ('4213', 'เอราวัณ', 'Erawan', '42');
INSERT INTO `district` VALUES ('4214', 'หนองหิน', 'Nong Hin', '42');
INSERT INTO `district` VALUES ('4301', 'เมืองหนองคาย', 'Mueang Nong Khai', '43');
INSERT INTO `district` VALUES ('4302', 'ท่าบ่อ', 'Tha Bo', '43');
INSERT INTO `district` VALUES ('4305', 'โพนพิสัย', 'Phon Phisai', '43');
INSERT INTO `district` VALUES ('4307', 'ศรีเชียงใหม่', 'Si Chiang Mai', '43');
INSERT INTO `district` VALUES ('4308', 'สังคม', 'Sangkhom', '43');
INSERT INTO `district` VALUES ('4314', 'สระใคร', 'Sakhrai', '43');
INSERT INTO `district` VALUES ('4315', 'เฝ้าไร่', 'Fao Rai', '43');
INSERT INTO `district` VALUES ('4316', 'รัตนวาปี', 'Rattanawapi', '43');
INSERT INTO `district` VALUES ('4317', 'โพธิ์ตาก', 'Pho Tak', '43');
INSERT INTO `district` VALUES ('4401', 'เมืองมหาสารคาม', 'Mueang Maha Sarakham', '44');
INSERT INTO `district` VALUES ('4402', 'แกดำ', 'Kae Dam', '44');
INSERT INTO `district` VALUES ('4403', 'โกสุมพิสัย', 'Kosum Phisai', '44');
INSERT INTO `district` VALUES ('4404', 'กันทรวิชัย', 'Kantharawichai', '44');
INSERT INTO `district` VALUES ('4405', 'เชียงยืน', 'Kantharawichai', '44');
INSERT INTO `district` VALUES ('4406', 'บรบือ', 'Borabue', '44');
INSERT INTO `district` VALUES ('4407', 'นาเชือก', 'Na Chueak', '44');
INSERT INTO `district` VALUES ('4408', 'พยัคฆภูมิพิสัย', 'Phayakkhaphum Phisai', '44');
INSERT INTO `district` VALUES ('4409', 'วาปีปทุม', 'Wapi Pathum', '44');
INSERT INTO `district` VALUES ('4410', 'นาดูน', 'Na Dun', '44');
INSERT INTO `district` VALUES ('4411', 'ยางสีสุราช', 'Yang Sisurat', '44');
INSERT INTO `district` VALUES ('4412', 'กุดรัง', 'Kut Rang', '44');
INSERT INTO `district` VALUES ('4413', 'ชื่นชม', 'Chuen Chom', '44');
INSERT INTO `district` VALUES ('4501', 'เมืองร้อยเอ็ด', 'Mueang Roi Et', '45');
INSERT INTO `district` VALUES ('4502', 'เกษตรวิสัย', 'Kaset Wisai', '45');
INSERT INTO `district` VALUES ('4503', 'ปทุมรัตต์', 'Pathum Rat', '45');
INSERT INTO `district` VALUES ('4504', 'จตุรพักตรพิมาน', 'Chaturaphak Phiman', '45');
INSERT INTO `district` VALUES ('4505', 'ธวัชบุรี', 'Thawat Buri', '45');
INSERT INTO `district` VALUES ('4506', 'พนมไพร', 'Phanom Phrai', '45');
INSERT INTO `district` VALUES ('4507', 'โพนทอง', 'Phon Thong', '45');
INSERT INTO `district` VALUES ('4508', 'โพธิ์ชัย', 'Pho Chai', '45');
INSERT INTO `district` VALUES ('4509', 'หนองพอก', 'Nong Phok', '45');
INSERT INTO `district` VALUES ('4510', 'เสลภูมิ', 'Selaphum', '45');
INSERT INTO `district` VALUES ('4511', 'สุวรรณภูมิ', 'Suwannaphum', '45');
INSERT INTO `district` VALUES ('4512', 'เมืองสรวง', 'Mueang Suang', '45');
INSERT INTO `district` VALUES ('4513', 'โพนทราย', 'Phon Sai', '45');
INSERT INTO `district` VALUES ('4514', 'อาจสามารถ', 'At Samat', '45');
INSERT INTO `district` VALUES ('4515', 'เมยวดี', 'Moei Wadi', '45');
INSERT INTO `district` VALUES ('4516', 'ศรีสมเด็จ', 'Si Somdet', '45');
INSERT INTO `district` VALUES ('4517', 'จังหาร', 'Changhan', '45');
INSERT INTO `district` VALUES ('4518', 'เชียงขวัญ', 'Chiang Khwan', '45');
INSERT INTO `district` VALUES ('4519', 'หนองฮี', 'Nong Hi', '45');
INSERT INTO `district` VALUES ('4520', 'ทุ่งเขาหลวง', 'Thung Khao Luangกิ่', '45');
INSERT INTO `district` VALUES ('4601', 'เมืองกาฬสินธุ์', 'Mueang Kalasin', '46');
INSERT INTO `district` VALUES ('4602', 'นามน', 'Na Mon', '46');
INSERT INTO `district` VALUES ('4603', 'กมลาไสย', 'Kamalasai', '46');
INSERT INTO `district` VALUES ('4604', 'ร่องคำ', 'Rong Kham', '46');
INSERT INTO `district` VALUES ('4605', 'กุฉินารายณ์', 'Kuchinarai', '46');
INSERT INTO `district` VALUES ('4606', 'เขาวง', 'Khao Wong', '46');
INSERT INTO `district` VALUES ('4607', 'ยางตลาด', 'Yang Talat', '46');
INSERT INTO `district` VALUES ('4608', 'ห้วยเม็ก', 'Huai Mek', '46');
INSERT INTO `district` VALUES ('4609', 'สหัสขันธ์', 'Sahatsakhan', '46');
INSERT INTO `district` VALUES ('4610', 'คำม่วง', 'Kham Muang', '46');
INSERT INTO `district` VALUES ('4611', 'ท่าคันโท', 'Tha Khantho', '46');
INSERT INTO `district` VALUES ('4612', 'หนองกุงศรี', 'Nong Kung Si', '46');
INSERT INTO `district` VALUES ('4613', 'สมเด็จ', 'Somdet', '46');
INSERT INTO `district` VALUES ('4614', 'ห้วยผึ้ง', 'Huai Phueng', '46');
INSERT INTO `district` VALUES ('4615', 'สามชัย', 'Sam Chai', '46');
INSERT INTO `district` VALUES ('4616', 'นาคู', 'Na Khu', '46');
INSERT INTO `district` VALUES ('4617', 'ดอนจาน', 'Don Chan', '46');
INSERT INTO `district` VALUES ('4618', 'ฆ้องชัย', 'Khong Chai', '46');
INSERT INTO `district` VALUES ('4701', 'เมืองสกลนคร', 'Mueang Sakon Nakhon', '47');
INSERT INTO `district` VALUES ('4702', 'กุสุมาลย์', 'Kusuman', '47');
INSERT INTO `district` VALUES ('4703', 'กุดบาก', 'Kut Bak', '47');
INSERT INTO `district` VALUES ('4704', 'พรรณานิคม', 'Phanna Nikhom', '47');
INSERT INTO `district` VALUES ('4705', 'พังโคน', 'Phang Khon', '47');
INSERT INTO `district` VALUES ('4706', 'วาริชภูมิ', 'Waritchaphum', '47');
INSERT INTO `district` VALUES ('4707', 'นิคมน้ำอูน', 'Nikhom Nam Un', '47');
INSERT INTO `district` VALUES ('4708', 'วานรนิวาส', 'Wanon Niwat', '47');
INSERT INTO `district` VALUES ('4709', 'คำตากล้า', 'Kham Ta Kla', '47');
INSERT INTO `district` VALUES ('4710', 'บ้านม่วง', 'Ban Muang', '47');
INSERT INTO `district` VALUES ('4711', 'อากาศอำนวย', 'Akat Amnuai', '47');
INSERT INTO `district` VALUES ('4712', 'สว่างแดนดิน', 'Sawang Daen Din', '47');
INSERT INTO `district` VALUES ('4713', 'ส่องดาว', 'Song Dao', '47');
INSERT INTO `district` VALUES ('4714', 'เต่างอย', 'Tao Ngoi', '47');
INSERT INTO `district` VALUES ('4715', 'โคกศรีสุพรรณ', 'Khok Si Suphan', '47');
INSERT INTO `district` VALUES ('4716', 'เจริญศิลป์', 'Charoen Sin', '47');
INSERT INTO `district` VALUES ('4717', 'โพนนาแก้ว', 'Phon Na Kaeo', '47');
INSERT INTO `district` VALUES ('4718', 'ภูพาน', 'Phu Phan', '47');
INSERT INTO `district` VALUES ('4801', 'เมืองนครพนม', 'Mueang Nakhon Phanom', '48');
INSERT INTO `district` VALUES ('4802', 'ปลาปาก', 'Pla Pak', '48');
INSERT INTO `district` VALUES ('4803', 'ท่าอุเทน', 'Tha Uthen', '48');
INSERT INTO `district` VALUES ('4804', 'บ้านแพง', 'Ban Phaeng', '48');
INSERT INTO `district` VALUES ('4805', 'ธาตุพนม', 'That Phanom', '48');
INSERT INTO `district` VALUES ('4806', 'เรณูนคร', 'Renu Nakhon', '48');
INSERT INTO `district` VALUES ('4807', 'นาแก', 'Na Kae', '48');
INSERT INTO `district` VALUES ('4808', 'ศรีสงคราม', 'Si Songkhram', '48');
INSERT INTO `district` VALUES ('4809', 'นาหว้า', 'Na Wa', '48');
INSERT INTO `district` VALUES ('4810', 'โพนสวรรค์', 'Phon Sawan', '48');
INSERT INTO `district` VALUES ('4811', 'นาทม', 'Na Thom', '48');
INSERT INTO `district` VALUES ('4812', 'วังยาง', 'Wang Yang', '48');
INSERT INTO `district` VALUES ('4901', 'เมืองมุกดาหาร', 'Mueang Mukdahan', '49');
INSERT INTO `district` VALUES ('4902', 'นิคมคำสร้อย', 'Nikhom Kham Soi', '49');
INSERT INTO `district` VALUES ('4903', 'ดอนตาล', 'Don Tan', '49');
INSERT INTO `district` VALUES ('4904', 'ดงหลวง', 'Dong Luang', '49');
INSERT INTO `district` VALUES ('4905', 'คำชะอี', 'Khamcha-i', '49');
INSERT INTO `district` VALUES ('4906', 'หว้านใหญ่', 'Wan Yai', '49');
INSERT INTO `district` VALUES ('4907', 'หนองสูง', 'Nong Sung', '49');
INSERT INTO `district` VALUES ('5001', 'เมืองเชียงใหม่', 'Mueang Chiang Mai', '50');
INSERT INTO `district` VALUES ('5002', 'จอมทอง', 'Chom Thong', '50');
INSERT INTO `district` VALUES ('5003', 'แม่แจ่ม', 'Mae Chaem', '50');
INSERT INTO `district` VALUES ('5004', 'เชียงดาว', 'Chiang Dao', '50');
INSERT INTO `district` VALUES ('5005', 'ดอยสะเก็ด', 'Doi Saket', '50');
INSERT INTO `district` VALUES ('5006', 'แม่แตง', 'Mae Taeng', '50');
INSERT INTO `district` VALUES ('5007', 'แม่ริม', 'Mae Rim', '50');
INSERT INTO `district` VALUES ('5008', 'สะเมิง', 'Samoeng', '50');
INSERT INTO `district` VALUES ('5009', 'ฝาง', 'Fang', '50');
INSERT INTO `district` VALUES ('5010', 'แม่อาย', 'Mae Ai', '50');
INSERT INTO `district` VALUES ('5011', 'พร้าว', 'Phrao', '50');
INSERT INTO `district` VALUES ('5012', 'สันป่าตอง', 'San Pa Tong', '50');
INSERT INTO `district` VALUES ('5013', 'สันกำแพง', 'San Kamphaeng', '50');
INSERT INTO `district` VALUES ('5014', 'สันทราย', 'San Sai', '50');
INSERT INTO `district` VALUES ('5015', 'หางดง', 'Hang Dong', '50');
INSERT INTO `district` VALUES ('5016', 'ฮอด', 'Hot', '50');
INSERT INTO `district` VALUES ('5017', 'ดอยเต่า', 'Doi Tao', '50');
INSERT INTO `district` VALUES ('5018', 'อมก๋อย', 'Omkoi', '50');
INSERT INTO `district` VALUES ('5019', 'สารภี', 'Saraphi', '50');
INSERT INTO `district` VALUES ('5020', 'เวียงแหง', 'Wiang Haeng', '50');
INSERT INTO `district` VALUES ('5021', 'ไชยปราการ', 'Chai Prakan', '50');
INSERT INTO `district` VALUES ('5022', 'แม่วาง', 'Mae Wang', '50');
INSERT INTO `district` VALUES ('5023', 'แม่ออน', 'Mae On', '50');
INSERT INTO `district` VALUES ('5024', 'ดอยหล่อ', 'Doi Lo', '50');
INSERT INTO `district` VALUES ('5025', 'กัลยาณิวัฒนา', 'Kalayani Watthana', '50');
INSERT INTO `district` VALUES ('5101', 'เมืองลำพูน', 'Mueang Lamphun', '51');
INSERT INTO `district` VALUES ('5102', 'แม่ทา', 'Mae Tha', '51');
INSERT INTO `district` VALUES ('5103', 'บ้านโฮ่ง', 'Ban Hong', '51');
INSERT INTO `district` VALUES ('5104', 'ลี้', 'Li', '51');
INSERT INTO `district` VALUES ('5105', 'ทุ่งหัวช้าง', 'Thung Hua Chang', '51');
INSERT INTO `district` VALUES ('5106', 'ป่าซาง', 'Pa Sang', '51');
INSERT INTO `district` VALUES ('5107', 'บ้านธิ', 'Ban Thi', '51');
INSERT INTO `district` VALUES ('5108', 'เวียงหนองล่อง', 'Wiang Nong Long', '51');
INSERT INTO `district` VALUES ('5201', 'เมืองลำปาง', 'Mueang Lampang', '52');
INSERT INTO `district` VALUES ('5202', 'แม่เมาะ', 'Mae Mo', '52');
INSERT INTO `district` VALUES ('5203', 'เกาะคา', 'Ko Kha', '52');
INSERT INTO `district` VALUES ('5204', 'เสริมงาม', 'Soem Ngam', '52');
INSERT INTO `district` VALUES ('5205', 'งาว', 'Ngao', '52');
INSERT INTO `district` VALUES ('5206', 'แจ้ห่ม', 'Chae Hom', '52');
INSERT INTO `district` VALUES ('5207', 'วังเหนือ', 'Wang Nuea', '52');
INSERT INTO `district` VALUES ('5208', 'เถิน', 'Thoen', '52');
INSERT INTO `district` VALUES ('5209', 'แม่พริก', 'Mae Phrik', '52');
INSERT INTO `district` VALUES ('5210', 'แม่ทะ', 'Mae Tha', '52');
INSERT INTO `district` VALUES ('5211', 'สบปราบ', 'Sop Prap', '52');
INSERT INTO `district` VALUES ('5212', 'ห้างฉัตร', 'Hang Chat', '52');
INSERT INTO `district` VALUES ('5213', 'เมืองปาน', 'Mueang Pan', '52');
INSERT INTO `district` VALUES ('5301', 'เมืองอุตรดิตถ์', 'Mueang Uttaradit', '53');
INSERT INTO `district` VALUES ('5302', 'ตรอน', 'Tron', '53');
INSERT INTO `district` VALUES ('5303', 'ท่าปลา', 'Tha Pla', '53');
INSERT INTO `district` VALUES ('5304', 'น้ำปาด', 'Nam Pat', '53');
INSERT INTO `district` VALUES ('5305', 'ฟากท่า', 'Fak Tha', '53');
INSERT INTO `district` VALUES ('5306', 'บ้านโคก', 'Ban Khok', '53');
INSERT INTO `district` VALUES ('5307', 'พิชัย', 'Phichai', '53');
INSERT INTO `district` VALUES ('5308', 'ลับแล', 'Laplae', '53');
INSERT INTO `district` VALUES ('5309', 'ทองแสนขัน', 'Thong Saen Khan', '53');
INSERT INTO `district` VALUES ('5401', 'เมืองแพร่', 'Mueang Phrae', '54');
INSERT INTO `district` VALUES ('5402', 'ร้องกวาง', 'Rong Kwang', '54');
INSERT INTO `district` VALUES ('5403', 'ลอง', 'Long', '54');
INSERT INTO `district` VALUES ('5404', 'สูงเม่น', 'Sung Men', '54');
INSERT INTO `district` VALUES ('5405', 'เด่นชัย', 'Den Chai', '54');
INSERT INTO `district` VALUES ('5406', 'สอง', 'Song', '54');
INSERT INTO `district` VALUES ('5407', 'วังชิ้น', 'Wang Chin', '54');
INSERT INTO `district` VALUES ('5408', 'หนองม่วงไข่', 'Nong Muang Khai', '54');
INSERT INTO `district` VALUES ('5501', 'เมืองน่าน', 'Mueang Nan', '55');
INSERT INTO `district` VALUES ('5502', 'แม่จริม', 'Mae Charim', '55');
INSERT INTO `district` VALUES ('5503', 'บ้านหลวง', 'Ban Luang', '55');
INSERT INTO `district` VALUES ('5504', 'นาน้อย', 'Na Noi', '55');
INSERT INTO `district` VALUES ('5505', 'ปัว', 'Pua', '55');
INSERT INTO `district` VALUES ('5506', 'ท่าวังผา', 'Tha Wang Pha', '55');
INSERT INTO `district` VALUES ('5507', 'เวียงสา', 'Wiang Sa', '55');
INSERT INTO `district` VALUES ('5508', 'ทุ่งช้าง', 'Thung Chang', '55');
INSERT INTO `district` VALUES ('5509', 'เชียงกลาง', 'Chiang Klang', '55');
INSERT INTO `district` VALUES ('5510', 'นาหมื่น', 'Na Muen', '55');
INSERT INTO `district` VALUES ('5511', 'สันติสุข', 'Santi Suk', '55');
INSERT INTO `district` VALUES ('5512', 'บ่อเกลือ', 'Bo Kluea', '55');
INSERT INTO `district` VALUES ('5513', 'สองแคว', 'Song Khwae', '55');
INSERT INTO `district` VALUES ('5514', 'ภูเพียง', 'Phu Phiang', '55');
INSERT INTO `district` VALUES ('5515', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat', '55');
INSERT INTO `district` VALUES ('5601', 'เมืองพะเยา', 'Mueang Phayao', '56');
INSERT INTO `district` VALUES ('5602', 'จุน', 'Chun', '56');
INSERT INTO `district` VALUES ('5603', 'เชียงคำ', 'Chiang Kham', '56');
INSERT INTO `district` VALUES ('5604', 'เชียงม่วน', 'Chiang Muan', '56');
INSERT INTO `district` VALUES ('5605', 'ดอกคำใต้', 'Dok Khamtai', '56');
INSERT INTO `district` VALUES ('5606', 'ปง', 'Pong', '56');
INSERT INTO `district` VALUES ('5607', 'แม่ใจ', 'Mae Chai', '56');
INSERT INTO `district` VALUES ('5608', 'ภูซาง', 'Phu Sang', '56');
INSERT INTO `district` VALUES ('5609', 'ภูกามยาว', 'Phu Kamyao', '56');
INSERT INTO `district` VALUES ('5701', 'เมืองเชียงราย', 'Mueang Chiang Rai', '57');
INSERT INTO `district` VALUES ('5702', 'เวียงชัย', 'Wiang Chai', '57');
INSERT INTO `district` VALUES ('5703', 'เชียงของ', 'Chiang Khong', '57');
INSERT INTO `district` VALUES ('5704', 'เทิง', 'Thoeng', '57');
INSERT INTO `district` VALUES ('5705', 'พาน', 'Phan', '57');
INSERT INTO `district` VALUES ('5706', 'ป่าแดด', 'Pa Daet', '57');
INSERT INTO `district` VALUES ('5707', 'แม่จัน', 'Mae Chan', '57');
INSERT INTO `district` VALUES ('5708', 'เชียงแสน', 'Chiang Saen', '57');
INSERT INTO `district` VALUES ('5709', 'แม่สาย', 'Mae Sai', '57');
INSERT INTO `district` VALUES ('5710', 'แม่สรวย', 'Mae Suai', '57');
INSERT INTO `district` VALUES ('5711', 'เวียงป่าเป้า', 'Wiang Pa Pao', '57');
INSERT INTO `district` VALUES ('5712', 'พญาเม็งราย', 'Phaya Mengrai', '57');
INSERT INTO `district` VALUES ('5713', 'เวียงแก่น', 'Wiang Kaen', '57');
INSERT INTO `district` VALUES ('5714', 'ขุนตาล', 'Khun Tan', '57');
INSERT INTO `district` VALUES ('5715', 'แม่ฟ้าหลวง', 'Mae Fa Luang', '57');
INSERT INTO `district` VALUES ('5716', 'แม่ลาว', 'Mae Lao', '57');
INSERT INTO `district` VALUES ('5717', 'เวียงเชียงรุ้ง', 'Wiang Chiang Rung', '57');
INSERT INTO `district` VALUES ('5718', 'ดอยหลวง', 'Doi Luang', '57');
INSERT INTO `district` VALUES ('5801', 'เมืองแม่ฮ่องสอน', 'Mueang Mae Hong Son', '58');
INSERT INTO `district` VALUES ('5802', 'ขุนยวม', 'Khun Yuam', '58');
INSERT INTO `district` VALUES ('5803', 'ปาย', 'Pai', '58');
INSERT INTO `district` VALUES ('5804', 'แม่สะเรียง', 'Mae Sariang', '58');
INSERT INTO `district` VALUES ('5805', 'แม่ลาน้อย', 'Mae La Noi', '58');
INSERT INTO `district` VALUES ('5806', 'สบเมย', 'Sop Moei', '58');
INSERT INTO `district` VALUES ('5807', 'ปางมะผ้า', 'Pang Mapha', '58');
INSERT INTO `district` VALUES ('6001', 'เมืองนครสวรรค์', 'Mueang Nakhon Sawan', '60');
INSERT INTO `district` VALUES ('6002', 'โกรกพระ', 'Krok Phra', '60');
INSERT INTO `district` VALUES ('6003', 'ชุมแสง', 'Chum Saeng', '60');
INSERT INTO `district` VALUES ('6004', 'หนองบัว', 'Nong Bua', '60');
INSERT INTO `district` VALUES ('6005', 'บรรพตพิสัย', 'Banphot Phisai', '60');
INSERT INTO `district` VALUES ('6006', 'เก้าเลี้ยว', 'Kao Liao', '60');
INSERT INTO `district` VALUES ('6007', 'ตาคลี', 'Takhli', '60');
INSERT INTO `district` VALUES ('6008', 'ท่าตะโก', 'Takhli', '60');
INSERT INTO `district` VALUES ('6009', 'ไพศาลี', 'Phaisali', '60');
INSERT INTO `district` VALUES ('6010', 'พยุหะคีรี', 'Phayuha Khiri', '60');
INSERT INTO `district` VALUES ('6011', 'ลาดยาว', 'Phayuha Khiri', '60');
INSERT INTO `district` VALUES ('6012', 'ตากฟ้า', 'Tak Fa', '60');
INSERT INTO `district` VALUES ('6013', 'แม่วงก์', 'Mae Wong', '60');
INSERT INTO `district` VALUES ('6014', 'แม่เปิน', 'Mae Poen', '60');
INSERT INTO `district` VALUES ('6015', 'ชุมตาบง', 'Chum Ta Bong', '60');
INSERT INTO `district` VALUES ('6101', 'เมืองอุทัยธานี', 'Mueang Uthai Thani', '61');
INSERT INTO `district` VALUES ('6102', 'ทัพทัน', 'Thap Than', '61');
INSERT INTO `district` VALUES ('6103', 'สว่างอารมณ์', 'Sawang Arom', '61');
INSERT INTO `district` VALUES ('6104', 'หนองฉาง', 'Nong Chang', '61');
INSERT INTO `district` VALUES ('6105', 'หนองขาหย่าง', 'Nong Khayang', '61');
INSERT INTO `district` VALUES ('6106', 'บ้านไร่', 'Ban Rai', '61');
INSERT INTO `district` VALUES ('6107', 'ลานสัก', 'Lan Sak', '61');
INSERT INTO `district` VALUES ('6108', 'ห้วยคต', 'Huai Khot', '61');
INSERT INTO `district` VALUES ('6201', 'เมืองกำแพงเพชร', 'Mueang Kamphaeng Phet', '62');
INSERT INTO `district` VALUES ('6202', 'ไทรงาม', 'Sai Ngam', '62');
INSERT INTO `district` VALUES ('6203', 'คลองลาน', 'Khlong Lan', '62');
INSERT INTO `district` VALUES ('6204', 'ขาณุวรลักษบุรี', 'Khanu Woralaksaburi', '62');
INSERT INTO `district` VALUES ('6205', 'คลองขลุง', 'Khlong Khlung', '62');
INSERT INTO `district` VALUES ('6206', 'พรานกระต่าย', 'Phran Kratai', '62');
INSERT INTO `district` VALUES ('6207', 'ลานกระบือ', 'Lan Krabue', '62');
INSERT INTO `district` VALUES ('6208', 'ทรายทองวัฒนา', 'Sai Thong Watthana', '62');
INSERT INTO `district` VALUES ('6209', 'ปางศิลาทอง', 'Pang Sila Thong', '62');
INSERT INTO `district` VALUES ('6210', 'บึงสามัคคี', 'Bueng Samakkhi', '62');
INSERT INTO `district` VALUES ('6211', 'โกสัมพีนคร', 'Kosamphi Nakhon', '62');
INSERT INTO `district` VALUES ('6301', 'เมืองตาก', 'Mueang Tak', '63');
INSERT INTO `district` VALUES ('6302', 'บ้านตาก', 'Ban Tak', '63');
INSERT INTO `district` VALUES ('6303', 'สามเงา', 'Sam Ngao', '63');
INSERT INTO `district` VALUES ('6304', 'แม่ระมาด', 'Mae Ramat', '63');
INSERT INTO `district` VALUES ('6305', 'ท่าสองยาง', 'Tha Song Yang', '63');
INSERT INTO `district` VALUES ('6306', 'แม่สอด', 'Mae Sot', '63');
INSERT INTO `district` VALUES ('6307', 'พบพระ', 'Phop Phra', '63');
INSERT INTO `district` VALUES ('6308', 'อุ้มผาง', 'Umphang', '63');
INSERT INTO `district` VALUES ('6309', 'วังเจ้า', 'Wang Chao', '63');
INSERT INTO `district` VALUES ('6401', 'เมืองสุโขทัย', 'Mueang Sukhothai', '64');
INSERT INTO `district` VALUES ('6402', 'บ้านด่านลานหอย', 'Ban Dan Lan Hoi', '64');
INSERT INTO `district` VALUES ('6403', 'คีรีมาศ', 'Khiri Mat', '64');
INSERT INTO `district` VALUES ('6404', 'กงไกรลาศ', 'Kong Krailat', '64');
INSERT INTO `district` VALUES ('6405', 'ศรีสัชนาลัย', 'Si Satchanalai', '64');
INSERT INTO `district` VALUES ('6406', 'ศรีสำโรง', 'Si Samrong', '64');
INSERT INTO `district` VALUES ('6407', 'สวรรคโลก', 'Sawankhalok', '64');
INSERT INTO `district` VALUES ('6408', 'ศรีนคร', 'Si Nakhon', '64');
INSERT INTO `district` VALUES ('6409', 'ทุ่งเสลี่ยม', 'Thung Saliam', '64');
INSERT INTO `district` VALUES ('6501', 'เมืองพิษณุโลก', 'Mueang Phitsanulok', '65');
INSERT INTO `district` VALUES ('6502', 'นครไทย', 'Nakhon Thai', '65');
INSERT INTO `district` VALUES ('6503', 'ชาติตระการ', 'Chat Trakan', '65');
INSERT INTO `district` VALUES ('6504', 'บางระกำ', 'Bang Rakam', '65');
INSERT INTO `district` VALUES ('6505', 'บางกระทุ่ม', 'Bang Krathum', '65');
INSERT INTO `district` VALUES ('6506', 'พรหมพิราม', 'Phrom Phiram', '65');
INSERT INTO `district` VALUES ('6507', 'วัดโบสถ์', 'Wat Bot', '65');
INSERT INTO `district` VALUES ('6508', 'วังทอง', 'Wang Thong', '65');
INSERT INTO `district` VALUES ('6509', 'เนินมะปราง', 'Noen Maprang', '65');
INSERT INTO `district` VALUES ('6601', 'เมืองพิจิตร', 'Mueang Phichit', '66');
INSERT INTO `district` VALUES ('6602', 'วังทรายพูน', 'Wang Sai Phun', '66');
INSERT INTO `district` VALUES ('6603', 'โพธิ์ประทับช้าง', 'Pho Prathap Chang', '66');
INSERT INTO `district` VALUES ('6604', 'ตะพานหิน', 'Taphan Hin', '66');
INSERT INTO `district` VALUES ('6605', 'บางมูลนาก', 'Bang Mun Nak', '66');
INSERT INTO `district` VALUES ('6606', 'โพทะเล', 'Pho Thale', '66');
INSERT INTO `district` VALUES ('6607', 'สามง่าม', 'Sam Ngam', '66');
INSERT INTO `district` VALUES ('6608', 'ทับคล้อ', 'Tap Khlo', '66');
INSERT INTO `district` VALUES ('6609', 'สากเหล็ก', 'Sak Lek', '66');
INSERT INTO `district` VALUES ('6610', 'บึงนาราง', 'Bueng Na Rang', '66');
INSERT INTO `district` VALUES ('6611', 'ดงเจริญ', 'Dong Charoen', '66');
INSERT INTO `district` VALUES ('6612', 'วชิรบารมี', 'Wachirabarami', '66');
INSERT INTO `district` VALUES ('6701', 'เมืองเพชรบูรณ์', 'Mueang Phetchabun', '67');
INSERT INTO `district` VALUES ('6702', 'ชนแดน', 'Chon Daen', '67');
INSERT INTO `district` VALUES ('6703', 'หล่มสัก', 'Lom Sak', '67');
INSERT INTO `district` VALUES ('6704', 'หล่มเก่า', 'Lom Kao', '67');
INSERT INTO `district` VALUES ('6705', 'วิเชียรบุรี', 'Wichian Buri', '67');
INSERT INTO `district` VALUES ('6706', 'ศรีเทพ', 'Si Thep', '67');
INSERT INTO `district` VALUES ('6707', 'หนองไผ่', 'Nong Phai', '67');
INSERT INTO `district` VALUES ('6708', 'บึงสามพัน', 'Bueng Sam Phan', '67');
INSERT INTO `district` VALUES ('6709', 'น้ำหนาว', 'Nam Nao', '67');
INSERT INTO `district` VALUES ('6710', 'วังโป่ง', 'Wang Pong', '67');
INSERT INTO `district` VALUES ('6711', 'เขาค้อ', 'Khao Kho', '67');
INSERT INTO `district` VALUES ('7001', 'เมืองราชบุรี', 'Mueang Ratchaburi', '70');
INSERT INTO `district` VALUES ('7002', 'จอมบึง', 'Chom Bueng', '70');
INSERT INTO `district` VALUES ('7003', 'สวนผึ้ง', 'Suan Phueng', '70');
INSERT INTO `district` VALUES ('7004', 'ดำเนินสะดวก', 'Damnoen Saduak', '70');
INSERT INTO `district` VALUES ('7005', 'บ้านโป่ง', 'Ban Pong', '70');
INSERT INTO `district` VALUES ('7006', 'บางแพ', 'Bang Phae', '70');
INSERT INTO `district` VALUES ('7007', 'โพธาราม', 'Photharam', '70');
INSERT INTO `district` VALUES ('7008', 'ปากท่อ', 'Pak Tho', '70');
INSERT INTO `district` VALUES ('7009', 'วัดเพลง', 'Wat Phleng', '70');
INSERT INTO `district` VALUES ('7010', 'บ้านคา', 'Ban Kha', '70');
INSERT INTO `district` VALUES ('7101', 'เมืองกาญจนบุรี', 'Mueang Kanchanaburi', '71');
INSERT INTO `district` VALUES ('7102', 'ไทรโยค', 'Sai Yok', '71');
INSERT INTO `district` VALUES ('7103', 'บ่อพลอย', 'Bo Phloi', '71');
INSERT INTO `district` VALUES ('7104', 'ศรีสวัสดิ์', 'Si Sawat', '71');
INSERT INTO `district` VALUES ('7105', 'ท่ามะกา', 'Tha Maka', '71');
INSERT INTO `district` VALUES ('7106', 'ท่าม่วง', 'Tha Muang', '71');
INSERT INTO `district` VALUES ('7107', 'ทองผาภูมิ', 'Pha Phum', '71');
INSERT INTO `district` VALUES ('7108', 'สังขละบุรี', 'Sangkhla Buri', '71');
INSERT INTO `district` VALUES ('7109', 'พนมทวน', 'Phanom Thuan', '71');
INSERT INTO `district` VALUES ('7110', 'เลาขวัญ', 'Lao Khwan', '71');
INSERT INTO `district` VALUES ('7111', 'ด่านมะขามเตี้ย', 'Dan Makham Tia', '71');
INSERT INTO `district` VALUES ('7112', 'หนองปรือ', 'Nong Prue', '71');
INSERT INTO `district` VALUES ('7113', 'ห้วยกระเจา', 'Huai Krachao', '71');
INSERT INTO `district` VALUES ('7201', 'เมืองสุพรรณบุรี', 'Mueang Suphan Buri', '72');
INSERT INTO `district` VALUES ('7202', 'เดิมบางนางบวช', 'Doem Bang Nang Buat', '72');
INSERT INTO `district` VALUES ('7203', 'ด่านช้าง', 'Dan Chang', '72');
INSERT INTO `district` VALUES ('7204', 'บางปลาม้า', 'Bang Pla Ma', '72');
INSERT INTO `district` VALUES ('7205', 'ศรีประจันต์', 'Si Prachan', '72');
INSERT INTO `district` VALUES ('7206', 'ดอนเจดีย์', 'Don Chedi', '72');
INSERT INTO `district` VALUES ('7207', 'สองพี่น้อง', 'Song Phi Nong', '72');
INSERT INTO `district` VALUES ('7208', 'สามชุก', 'Sam Chuk', '72');
INSERT INTO `district` VALUES ('7209', 'อู่ทอง', 'U Thong', '72');
INSERT INTO `district` VALUES ('7210', 'หนองหญ้าไซ', 'Nong Ya Sai', '72');
INSERT INTO `district` VALUES ('7301', 'เมืองนครปฐม', 'Mueang Nakhon Pathom', '73');
INSERT INTO `district` VALUES ('7302', 'กำแพงแสน', 'Kamphaeng Saen', '73');
INSERT INTO `district` VALUES ('7303', 'นครชัยศรี', 'Nakhon Chai Si', '73');
INSERT INTO `district` VALUES ('7304', 'ดอนตูม', 'Don Tum', '73');
INSERT INTO `district` VALUES ('7305', 'บางเลน', 'Bang Len', '73');
INSERT INTO `district` VALUES ('7306', 'สามพราน', 'Sam Phran', '73');
INSERT INTO `district` VALUES ('7307', 'พุทธมณฑล', 'Phutthamonthon', '73');
INSERT INTO `district` VALUES ('7401', 'เมืองสมุทรสาคร', 'Mueang Samut Sakhon', '74');
INSERT INTO `district` VALUES ('7402', 'กระทุ่มแบน', 'Krathum Baen', '74');
INSERT INTO `district` VALUES ('7403', 'บ้านแพ้ว', 'Ban Phaeo', '74');
INSERT INTO `district` VALUES ('7501', 'เมืองสมุทรสงคราม', 'Mueang Samut Songkhram', '75');
INSERT INTO `district` VALUES ('7502', 'บางคนที', 'Bang Khonthi', '75');
INSERT INTO `district` VALUES ('7503', 'อัมพวา', 'Amphawa', '75');
INSERT INTO `district` VALUES ('7601', 'เมืองเพชรบุรี', 'Mueang Phetchaburi', '76');
INSERT INTO `district` VALUES ('7602', 'เขาย้อย', 'Khao Yoi', '76');
INSERT INTO `district` VALUES ('7603', 'หนองหญ้าปล้อง', 'Nong Ya Plong', '76');
INSERT INTO `district` VALUES ('7604', 'ชะอำ', 'Cha-am', '76');
INSERT INTO `district` VALUES ('7605', 'ท่ายาง', 'Tha Yang', '76');
INSERT INTO `district` VALUES ('7606', 'บ้านลาด', 'Ban Lat', '76');
INSERT INTO `district` VALUES ('7607', 'บ้านแหลม', 'Ban Laem', '76');
INSERT INTO `district` VALUES ('7608', 'แก่งกระจาน', 'Kaeng Krachan', '76');
INSERT INTO `district` VALUES ('7701', 'เมืองประจวบคีรีขันธ์', 'Mueang Prachuap Khiri Khan', '77');
INSERT INTO `district` VALUES ('7702', 'กุยบุรี', 'Kui Buri', '77');
INSERT INTO `district` VALUES ('7703', 'ทับสะแก', 'Thap Sakae', '77');
INSERT INTO `district` VALUES ('7704', 'บางสะพาน', 'Bang Saphan', '77');
INSERT INTO `district` VALUES ('7705', 'บางสะพานน้อย', 'Bang Saphan Noi', '77');
INSERT INTO `district` VALUES ('7706', 'ปราณบุรี', 'Pran Buri', '77');
INSERT INTO `district` VALUES ('7707', 'หัวหิน', 'Hua Hin', '77');
INSERT INTO `district` VALUES ('7708', 'สามร้อยยอด', 'Sam Roi Yot', '77');
INSERT INTO `district` VALUES ('8001', 'เมืองนครศรีธรรมราช', 'Mueang Nakhon Si Thammarat', '80');
INSERT INTO `district` VALUES ('8002', 'พรหมคีรี', 'Phrom Khiri', '80');
INSERT INTO `district` VALUES ('8003', 'ลานสกา', 'Lan Saka', '80');
INSERT INTO `district` VALUES ('8004', 'ฉวาง', 'Chawang', '80');
INSERT INTO `district` VALUES ('8005', 'พิปูน', 'Phipun', '80');
INSERT INTO `district` VALUES ('8006', 'เชียรใหญ่', 'Chian Yai', '80');
INSERT INTO `district` VALUES ('8007', 'ชะอวด', 'Cha-uat', '80');
INSERT INTO `district` VALUES ('8008', 'ท่าศาลา', 'Tha Sala', '80');
INSERT INTO `district` VALUES ('8009', 'ทุ่งสง', 'Thung Song', '80');
INSERT INTO `district` VALUES ('8010', 'นาบอน', 'Na Bon', '80');
INSERT INTO `district` VALUES ('8011', 'ทุ่งใหญ่', 'Thung Yai', '80');
INSERT INTO `district` VALUES ('8012', 'ปากพนัง', 'Pak Phanang', '80');
INSERT INTO `district` VALUES ('8013', 'ร่อนพิบูลย์', 'Ron Phibun', '80');
INSERT INTO `district` VALUES ('8014', 'สิชล', 'Sichon', '80');
INSERT INTO `district` VALUES ('8015', 'ขนอม', 'Khanom', '80');
INSERT INTO `district` VALUES ('8016', 'หัวไทร', 'Hua Sai', '80');
INSERT INTO `district` VALUES ('8017', 'บางขัน', 'Bang Khan', '80');
INSERT INTO `district` VALUES ('8018', 'ถ้ำพรรณรา', 'Tham Phannara', '80');
INSERT INTO `district` VALUES ('8019', 'จุฬาภรณ์', 'Chulabhorn', '80');
INSERT INTO `district` VALUES ('8020', 'พระพรหม', 'Phra Phrom', '80');
INSERT INTO `district` VALUES ('8021', 'นบพิตำ', 'Nopphitam', '80');
INSERT INTO `district` VALUES ('8022', 'ช้างกลาง', 'Chang Klang', '80');
INSERT INTO `district` VALUES ('8023', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat', '80');
INSERT INTO `district` VALUES ('8101', 'เมืองกระบี่', 'Mueang Krabi', '81');
INSERT INTO `district` VALUES ('8102', 'เขาพนม', 'Khao Phanom', '81');
INSERT INTO `district` VALUES ('8103', 'เกาะลันตา', 'Ko Lanta', '81');
INSERT INTO `district` VALUES ('8104', 'คลองท่อม', 'Khlong Thom', '81');
INSERT INTO `district` VALUES ('8105', 'อ่าวลึก', 'Ao Luek', '81');
INSERT INTO `district` VALUES ('8106', 'ปลายพระยา', 'Plai Phraya', '81');
INSERT INTO `district` VALUES ('8107', 'ลำทับ', 'Lam Thap', '81');
INSERT INTO `district` VALUES ('8108', 'เหนือคลอง', 'Nuea Khlong', '81');
INSERT INTO `district` VALUES ('8201', 'เมืองพังงา', 'Mueang Phang-nga', '82');
INSERT INTO `district` VALUES ('8202', 'เกาะยาว', 'Ko Yao', '82');
INSERT INTO `district` VALUES ('8203', 'กะปง', 'Kapong', '82');
INSERT INTO `district` VALUES ('8204', 'ตะกั่วทุ่ง', 'Takua Thung', '82');
INSERT INTO `district` VALUES ('8205', 'ตะกั่วป่า', 'Takua Pa', '82');
INSERT INTO `district` VALUES ('8206', 'คุระบุรี', 'Khura Buri', '82');
INSERT INTO `district` VALUES ('8207', 'ทับปุด', 'Thap Put', '82');
INSERT INTO `district` VALUES ('8208', 'ท้ายเหมือง', 'Thai Mueang', '82');
INSERT INTO `district` VALUES ('8301', 'เมืองภูเก็ต', 'Mueang Phuket', '83');
INSERT INTO `district` VALUES ('8302', 'กะทู้', 'Kathu', '83');
INSERT INTO `district` VALUES ('8303', 'ถลาง', 'Thalang', '83');
INSERT INTO `district` VALUES ('8401', 'เมืองสุราษฎร์ธานี', 'Mueang Surat Thani', '84');
INSERT INTO `district` VALUES ('8402', 'กาญจนดิษฐ์', 'Kanchanadit', '84');
INSERT INTO `district` VALUES ('8403', 'ดอนสัก', 'Don Sak', '84');
INSERT INTO `district` VALUES ('8404', 'เกาะสมุย', 'Ko Samui', '84');
INSERT INTO `district` VALUES ('8405', 'เกาะพะงัน', 'Ko Pha-ngan', '84');
INSERT INTO `district` VALUES ('8406', 'ไชยา', 'Chaiya', '84');
INSERT INTO `district` VALUES ('8407', 'ท่าชนะ', 'Tha Chana', '84');
INSERT INTO `district` VALUES ('8408', 'คีรีรัฐนิคม', 'Khiri Rat Nikhom', '84');
INSERT INTO `district` VALUES ('8409', 'บ้านตาขุน', 'Ban Ta Khun', '84');
INSERT INTO `district` VALUES ('8410', 'พนม', 'Phanom', '84');
INSERT INTO `district` VALUES ('8411', 'ท่าฉาง', 'Tha Chang', '84');
INSERT INTO `district` VALUES ('8412', 'บ้านนาสาร', 'Ban Na San', '84');
INSERT INTO `district` VALUES ('8413', 'บ้านนาเดิม', 'Ban Na Doem', '84');
INSERT INTO `district` VALUES ('8414', 'เคียนซา', 'Khian Sa', '84');
INSERT INTO `district` VALUES ('8415', 'เวียงสระ', 'Wiang Sa', '84');
INSERT INTO `district` VALUES ('8416', 'พระแสง', 'Phrasaeng', '84');
INSERT INTO `district` VALUES ('8417', 'พุนพิน', 'Phunphin', '84');
INSERT INTO `district` VALUES ('8418', 'ชัยบุรี', 'Chai Buri', '84');
INSERT INTO `district` VALUES ('8419', 'วิภาวดี', 'Vibhavadi', '84');
INSERT INTO `district` VALUES ('8501', 'เมืองระนอง', 'Mueang Ranong', '85');
INSERT INTO `district` VALUES ('8502', 'ละอุ่น', 'La-un', '85');
INSERT INTO `district` VALUES ('8503', 'กะเปอร์', 'Kapoe', '85');
INSERT INTO `district` VALUES ('8504', 'กระบุรี', 'Kra Buri', '85');
INSERT INTO `district` VALUES ('8505', 'สุขสำราญ', 'Suk Samran', '85');
INSERT INTO `district` VALUES ('8601', 'เมืองชุมพร', 'Mueang Chumphon', '86');
INSERT INTO `district` VALUES ('8602', 'ท่าแซะ', 'Tha Sae', '86');
INSERT INTO `district` VALUES ('8603', 'ปะทิว', 'Pathio', '86');
INSERT INTO `district` VALUES ('8604', 'หลังสวน', 'Lang Suan', '86');
INSERT INTO `district` VALUES ('8605', 'ละแม', 'Lamae', '86');
INSERT INTO `district` VALUES ('8606', 'พะโต๊ะ', 'Phato', '86');
INSERT INTO `district` VALUES ('8607', 'สวี', 'Sawi', '86');
INSERT INTO `district` VALUES ('8608', 'ทุ่งตะโก', 'Thung Tako', '86');
INSERT INTO `district` VALUES ('9001', 'เมืองสงขลา', 'Mueang Songkhla', '90');
INSERT INTO `district` VALUES ('9002', 'สทิงพระ', 'Sathing Phra', '90');
INSERT INTO `district` VALUES ('9003', 'จะนะ', 'Chana', '90');
INSERT INTO `district` VALUES ('9004', 'นาทวี', 'Na Thawi', '90');
INSERT INTO `district` VALUES ('9005', 'เทพา', 'Thepha', '90');
INSERT INTO `district` VALUES ('9006', 'สะบ้าย้อย', 'Saba Yoi', '90');
INSERT INTO `district` VALUES ('9007', 'ระโนด', 'Ranot', '90');
INSERT INTO `district` VALUES ('9008', 'กระแสสินธุ์', 'Krasae Sin', '90');
INSERT INTO `district` VALUES ('9009', 'รัตภูมิ', 'Rattaphum', '90');
INSERT INTO `district` VALUES ('9010', 'สะเดา', 'Sadao', '90');
INSERT INTO `district` VALUES ('9011', 'หาดใหญ่', 'Hat Yai', '90');
INSERT INTO `district` VALUES ('9012', 'นาหม่อม', 'Na Mom', '90');
INSERT INTO `district` VALUES ('9013', 'ควนเนียง', 'Khuan Niang', '90');
INSERT INTO `district` VALUES ('9014', 'บางกล่ำ', 'Bang Klam', '90');
INSERT INTO `district` VALUES ('9015', 'สิงหนคร', 'Singhanakhon', '90');
INSERT INTO `district` VALUES ('9016', 'คลองหอยโข่ง', 'Khlong Hoi Khong', '90');
INSERT INTO `district` VALUES ('9101', 'เมืองสตูล', 'Mueang Satun', '91');
INSERT INTO `district` VALUES ('9102', 'ควนโดน', 'Khuan Don', '91');
INSERT INTO `district` VALUES ('9103', 'ควนกาหลง', 'Khuan Kalong', '91');
INSERT INTO `district` VALUES ('9104', 'ท่าแพ', 'Tha Phae', '91');
INSERT INTO `district` VALUES ('9105', 'ละงู', 'La-ngu', '91');
INSERT INTO `district` VALUES ('9106', 'ทุ่งหว้า', 'Thung Wa', '91');
INSERT INTO `district` VALUES ('9107', 'มะนัง', 'Manang', '91');
INSERT INTO `district` VALUES ('9201', 'เมืองตรัง', 'Mueang Trang', '92');
INSERT INTO `district` VALUES ('9202', 'กันตัง', 'Kantang', '92');
INSERT INTO `district` VALUES ('9203', 'ย่านตาขาว', 'Yan Ta Khao', '92');
INSERT INTO `district` VALUES ('9204', 'ปะเหลียน', 'Palian', '92');
INSERT INTO `district` VALUES ('9205', 'สิเกา', 'Sikao', '92');
INSERT INTO `district` VALUES ('9206', 'ห้วยยอด', 'Huai Yot', '92');
INSERT INTO `district` VALUES ('9207', 'วังวิเศษ', 'Wang Wiset', '92');
INSERT INTO `district` VALUES ('9208', 'นาโยง', 'Na Yong', '92');
INSERT INTO `district` VALUES ('9209', 'รัษฎา', 'Ratsada', '92');
INSERT INTO `district` VALUES ('9210', 'หาดสำราญ', 'Hat Samran', '92');
INSERT INTO `district` VALUES ('9301', 'เมืองพัทลุง', 'Mueang Phatthalung', '93');
INSERT INTO `district` VALUES ('9302', 'กงหรา', 'Kong Ra', '93');
INSERT INTO `district` VALUES ('9303', 'เขาชัยสน', 'Khao Chaison', '93');
INSERT INTO `district` VALUES ('9304', 'ตะโหมด', 'Tamot', '93');
INSERT INTO `district` VALUES ('9305', 'ควนขนุน', 'Khuan Khanun', '93');
INSERT INTO `district` VALUES ('9306', 'ปากพะยูน', 'Pak Phayun', '93');
INSERT INTO `district` VALUES ('9307', 'ศรีบรรพต', 'Si Banphot', '93');
INSERT INTO `district` VALUES ('9308', 'ป่าบอน', 'Pa Bon', '93');
INSERT INTO `district` VALUES ('9309', 'บางแก้ว', 'Bang Kaeo', '93');
INSERT INTO `district` VALUES ('9310', 'ป่าพะยอม', 'Pa Phayom', '93');
INSERT INTO `district` VALUES ('9311', 'ศรีนครินทร์', 'Srinagarindra', '93');
INSERT INTO `district` VALUES ('9401', 'เมืองปัตตานี', 'Mueang Pattani', '94');
INSERT INTO `district` VALUES ('9402', 'โคกโพธิ์', 'Khok Pho', '94');
INSERT INTO `district` VALUES ('9403', 'หนองจิก', 'Nong Chik', '94');
INSERT INTO `district` VALUES ('9404', 'ปะนาเระ', 'Panare', '94');
INSERT INTO `district` VALUES ('9405', 'มายอ', 'Mayo', '94');
INSERT INTO `district` VALUES ('9406', 'ทุ่งยางแดง', 'Thung Yang Daeng', '94');
INSERT INTO `district` VALUES ('9407', 'สายบุรี', 'Sai Buri', '94');
INSERT INTO `district` VALUES ('9408', 'ไม้แก่น', 'Mai Kaen', '94');
INSERT INTO `district` VALUES ('9409', 'ยะหริ่ง', 'Yaring', '94');
INSERT INTO `district` VALUES ('9410', 'ยะรัง', 'Yarang', '94');
INSERT INTO `district` VALUES ('9411', 'กะพ้อ', 'Kapho', '94');
INSERT INTO `district` VALUES ('9412', 'แม่ลาน', 'Mae Lan', '94');
INSERT INTO `district` VALUES ('9501', 'เมืองยะลา', 'Mueang Yala', '95');
INSERT INTO `district` VALUES ('9502', 'เบตง', 'Betong', '95');
INSERT INTO `district` VALUES ('9503', 'บันนังสตา', 'Bannang Sata', '95');
INSERT INTO `district` VALUES ('9504', 'ธารโต', 'Than To', '95');
INSERT INTO `district` VALUES ('9505', 'ยะหา', 'Yaha', '95');
INSERT INTO `district` VALUES ('9506', 'รามัน', 'Raman', '95');
INSERT INTO `district` VALUES ('9507', 'กาบัง', 'Kabang', '95');
INSERT INTO `district` VALUES ('9508', 'กรงปินัง', 'Krong Pinang', '95');
INSERT INTO `district` VALUES ('9601', 'เมืองนราธิวาส', 'Mueang Narathiwat', '96');
INSERT INTO `district` VALUES ('9602', 'ตากใบ', 'Tak Bai', '96');
INSERT INTO `district` VALUES ('9603', 'บาเจาะ', 'Bacho', '96');
INSERT INTO `district` VALUES ('9604', 'ยี่งอ', 'Yi-ngo', '96');
INSERT INTO `district` VALUES ('9605', 'ระแงะ', 'Ra-ngae', '96');
INSERT INTO `district` VALUES ('9606', 'รือเสาะ', 'Rueso', '96');
INSERT INTO `district` VALUES ('9607', 'ศรีสาคร', 'Si Sakhon', '96');
INSERT INTO `district` VALUES ('9608', 'แว้ง', 'Waeng', '96');
INSERT INTO `district` VALUES ('9609', 'สุคิริน', 'Sukhirin', '96');
INSERT INTO `district` VALUES ('9610', 'สุไหงโก-ลก', 'Su-ngai Kolok', '96');
INSERT INTO `district` VALUES ('9611', 'สุไหงปาดี', 'Su-ngai Padi', '96');
INSERT INTO `district` VALUES ('9612', 'จะแนะ', 'Chanae', '96');
INSERT INTO `district` VALUES ('9613', 'เจาะไอร้อง', 'Cho-airong', '96');
